program main
	use circle_class_test
	implicit none
	call setup
	call funit_assertions
	call teardown
	call setup
	call radius_is_stored_properly
	call teardown
	call setup
	call area_varies_with_radius
	call teardown
end program